-- MySQL Script generated by MySQL Workbench
-- Sun Feb 28 18:43:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BookStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookStore` DEFAULT CHARACTER SET utf8 ;
USE `BookStore` ;

-- -----------------------------------------------------
-- Table `BookStore`.`BookInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`BookInventory` (
  `idBookInventory` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(45) NOT NULL,
  `book_quantity` VARCHAR(45) NOT NULL,
  `book_price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBookInventory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`customers` (
  `idcustomers` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_no` INT NOT NULL,
  PRIMARY KEY (`idcustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`card_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`card_details` (
  `idcard_details` INT NOT NULL AUTO_INCREMENT,
  `card_number` INT NOT NULL,
  `cardholder_name` VARCHAR(45) NOT NULL,
  `expiry` INT NOT NULL,
  `cvv` INT NOT NULL,
  PRIMARY KEY (`idcard_details`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`orders` (
  `idorders` INT NOT NULL AUTO_INCREMENT,
  `method_of_payment` VARCHAR(45) NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `customers_idcustomers` INT NOT NULL,
  `card_details_idcard_details` INT NOT NULL,
  `BookInventory_idBookInventory` INT NOT NULL,
  PRIMARY KEY (`idorders`),
  INDEX `fk_orders_customers_idx` (`customers_idcustomers` ASC) VISIBLE,
  INDEX `fk_orders_card_details1_idx` (`card_details_idcard_details` ASC) VISIBLE,
  INDEX `fk_orders_BookInventory1_idx` (`BookInventory_idBookInventory` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers`
    FOREIGN KEY (`customers_idcustomers`)
    REFERENCES `BookStore`.`customers` (`idcustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_card_details1`
    FOREIGN KEY (`card_details_idcard_details`)
    REFERENCES `BookStore`.`card_details` (`idcard_details`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_BookInventory1`
    FOREIGN KEY (`BookInventory_idBookInventory`)
    REFERENCES `BookStore`.`BookInventory` (`idBookInventory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookStore`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookStore`.`address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(6) NOT NULL,
  `customers_idcustomers` INT NOT NULL,
  PRIMARY KEY (`idaddress`),
  INDEX `fk_address_customers1_idx` (`customers_idcustomers` ASC) VISIBLE,
  CONSTRAINT `fk_address_customers1`
    FOREIGN KEY (`customers_idcustomers`)
    REFERENCES `BookStore`.`customers` (`idcustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
